"""Adding Edge metadata

Revision ID: 07f57ae3bbbe
Revises: 34b8a651f026
Create Date: 2026-04-03 18:28:07.500495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f57ae3bbbe'
down_revision = '34b8a651f026'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penalty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('relation', sa.String(), nullable=True))
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('relation')
        batch_op.drop_column('penalty')

    # ### end Alembic commands ###
