"""Minimal fixes 1.1

Revision ID: 26847ff5c00d
Revises: dc349db597ec
Create Date: 2026-04-04 12:37:09.269708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26847ff5c00d'
down_revision = 'dc349db597ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('graph_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.alter_column('graph_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
