"""Adding Edge Model

Revision ID: 34b8a651f026
Revises: 9e05071200ef
Create Date: 2026-04-03 18:07:52.854152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34b8a651f026'
down_revision = '9e05071200ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('edges',
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.drop_table('node_hierarchy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('node_hierarchy',
    sa.Column('parent_id', sa.INTEGER(), nullable=False),
    sa.Column('child_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.drop_table('edges')
    # ### end Alembic commands ###
