"""empty message

Revision ID: 51d820b6941c
Revises: 07f57ae3bbbe
Create Date: 2026-04-03 18:28:59.635580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d820b6941c'
down_revision = '07f57ae3bbbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.alter_column('penalty',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('relation',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.alter_column('relation',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('penalty',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
