"""Adding description to edges

Revision ID: 83690f81dc17
Revises: cd3de2f311c0
Create Date: 2026-04-06 10:45:30.120701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83690f81dc17'
down_revision = 'cd3de2f311c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
