"""Adding tasks to the graph

Revision ID: 8e8f8d45b3c8
Revises: 83690f81dc17
Create Date: 2026-04-07 16:24:01.071137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e8f8d45b3c8'
down_revision = '83690f81dc17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph', schema=None) as batch_op:
        batch_op.drop_column('task')

    # ### end Alembic commands ###
