"""empty message

Revision ID: 9bb5b86424fb
Revises: 26847ff5c00d
Create Date: 2026-04-04 21:30:21.563003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bb5b86424fb'
down_revision = '26847ff5c00d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_edge', ['graph_id', 'parent_id', 'child_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_constraint('unique_edge', type_='unique')

    # ### end Alembic commands ###
