"""Adding primary mark to nodes

Revision ID: cd3de2f311c0
Revises: 9bb5b86424fb
Create Date: 2026-04-05 18:23:43.599422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd3de2f311c0'
down_revision = '9bb5b86424fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_primary', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
