"""Several Changes; adding Graph model

Revision ID: dc349db597ec
Revises: 51d820b6941c
Create Date: 2026-04-04 12:26:09.739769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc349db597ec'
down_revision = '51d820b6941c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('graph_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'graph', ['graph_id'], ['id'])

    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'graph', ['graph_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nodes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('graph_id')

    with op.batch_alter_table('edges', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('graph_id')
        batch_op.drop_column('id')

    op.drop_table('graph')
    # ### end Alembic commands ###
